### ISSUE TITLE
Determine what properties we want for 0.1 milestone

### ISSUE THREAD

**Issue by dtauerbach** [EFForg/cryptobot-email#8]
Right now responding about whether an email is encrypted (to anyone) and signed (by anyone) is implemented, in html. Let's use this issue to create a list of desiridata for the first pass. Here's what I have from Micah's old list:

encrypted (to anyone)
encrypted (to us, properly)
signed
subject_leak (not sure what this is?)
pubkey_attached
pubkey_inline (presumably we don't need both)
pubkey_on_server
pubkey_weak (I think we can leave this off for 0.1)
pubkey_same_as_sig
using_mime

**Comment by micahflee** [comment]
Many people don't realize that PGP only encrypts the body an email and doesn't encrypt any headers, including the subject. Because of this it's best if subject lines are blank or nondescript. I was thinking subject_leak would be set if the subject is anything but "" and "Re: ", so we could link to info about this.

The only difference between pubkey_attached and pubkey_inline is that the bot will need to find this pubkey and import it. Maybe instead it can just be pubkey_included and the parser class.can also include pubkey, which would be the actual key to import.

And I agree, pubkey_weak can be for 0.2.

**Comment by dtauerbach** [comment]
That makes sense re: subject leak. We could instruct users to leave the subject blank. If the subject is blank they get a green check, if it's under or equal ot 4 characters but not blank they get a yellow, and if it's greater than 4 characters they get a red. Again, I am on board with linking to info, but think our main priority with this project should be the bot.

**Comment by micahflee** [comment]
For version 0.1, lets stick with:
- encrypted to the right key (done)
- encrypted to the wrong key (done)
- signed (halfway done)
- pubkey included
- pubkey on key server

**Comment by micahflee** [comment]
We have bugs open for these. Detecting signed (#15) and detecting pubkeys (#3) so I'm going to close this.
